FROM quay.io/hummingbird/nodejs:24 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM quay.io/hummingbird/nodejs:24 
WORKDIR /app
COPY package*.json ./
# not needed for svelte app
# RUN npm ci --omit=dev && \
#     npm cache clean --force
COPY --from=builder /app/build ./build
EXPOSE 3000
ENV NODE_ENV=production
ENV PORT=3000
ENV HOST=0.0.0.0
CMD ["node", "build/index.js"]